name: Wire Bot GitHub Action
on: push
jobs:
  post:
    name: Wire Bot GitHub Action
    runs-on: ubuntu-latest
    steps:
      - name: Cache data
        id: cache-data
        uses: actions/cache@v1
        with:
          path: data
          key: ${{runner.os}}-data
      - uses: actions/checkout@v1
      - name: Post a message
        uses: ./
        with:
          email: ${{secrets.WIRE_BOT_EMAIL}}
          password: ${{secrets.WIRE_BOT_PASSWORD}}
          conversation: '6936f0a3-be49-4f81-b4a7-d734661beff2'
          text: 'Hello, World!'
          permanent: 'true'
